---
- name: Configure Apache Web Server on Ubuntu 22.04
  hosts: all  # Replace with your server's hostname or IP address
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a sample HTML file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      notify: Restart Apache

    - name: Get external IP address using AWS metadata
      command: "curl -s http://169.254.169.254/latest/meta-data/public-ipv4"
      register: external_ip
      changed_when: false  # Mark the task as non-changing

    - name: Display external IP address
      debug:
        var: external_ip.stdout

    - name: Add external IP to Apache website
      lineinfile:
        path: /var/www/html/index.html
        line: "<p>External IP Address: {{ external_ip.stdout }}</p>"
      notify: Restart Apache
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        state: present
        
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install gnupg
      apt:
        name: gnupg
        state: present

    - name: Add Jenkins APT keyring
      shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc"
      args:
        executable: /bin/bash

    - name: Add Jenkins APT repository
      shell: sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      args:
        executable: /bin/bash

    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present
        
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Retrieve initialAdminPassword file
      fetch:
        src: /var/lib/jenkins/secrets/initialAdminPassword
        dest: "{{ playbook_dir }}/initialAdminPassword"
        flat: yes
        



  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
